#!/bin/bash
#####################################################-*-mode:shell-script-*-
##                                                                       ##
##                     Carnegie Mellon University                        ##
##                      Copyright (c) 2005-2008                          ##
##                        All Rights Reserved.                           ##
##                                                                       ##
##  Permission is hereby granted, free of charge, to use and distribute  ##
##  this software and its documentation without restriction, including   ##
##  without limitation the rights to use, copy, modify, merge, publish,  ##
##  distribute, sublicense, and/or sell copies of this work, and to      ##
##  permit persons to whom this work is furnished to do so, subject to   ##
##  the following conditions:                                            ##
##   1. The code must retain the above copyright notice, this list of    ##
##      conditions and the following disclaimer.                         ##
##   2. Any modifications must be clearly marked as such.                ##
##   3. Original authors' names are not deleted.                         ##
##   4. The authors' names are not used to endorse or promote products   ##
##      derived from this software without specific prior written        ##
##      permission.                                                      ##
##                                                                       ##
##  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         ##
##  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      ##
##  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   ##
##  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      ##
##  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    ##
##  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   ##
##  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          ##
##  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       ##
##  THIS SOFTWARE.                                                       ##
##                                                                       ##
###########################################################################
##                                                                       ##
##  Extract all the feats in one go (much faster)                        ##
##                                                                       ##
##  saved about 33 hours from a 39 hours voice build                     ##
##     and didn't require all utts to be festival at once                ##
##                                                                       ##
##  Redid this in Feb/Mar 2008 to make it use less disk space and time   ##
##                                                                       ##
###########################################################################
###########################################################################
##                                                                       ##
##  Author: Pallas13 (edsondasilvaguedes0@gmail) 2025                    ##
##  New version for Extraction feats and mcep for all phones             ##
##  of festival/coeffs, using parallel for multiples process.            ##
###########################################################################



if command -v parallel >&2; then
    echo parallel is available
else
    echo parallel is not available, please install in your system
    exit 0
fi

CPUS="$(nproc)"
make_all_feats() {
    DATABASE=$1
    rm festival/coeffs/cg_all.{feats,mcep}
    awk '{print $2}' "$DATABASE" | parallel -j"$CPUS" --bar --progress cat festival/coeffs/{}.feats >>festival/coeffs/cg_all.feats
    awk '{print $2}' "$DATABASE" | parallel -j"$CPUS" --bar --progress cat festival/coeffs/{}.mcep >>festival/coeffs/cg_all.mcep
    cut --complement -f2 -d" " festival/coeffs/cg_all.feats | sort -g >festival/coeffs/cg_all_sorted.feats
    cat festival/coeffs/cg_all.mcep | sort -g >festival/coeffs/cg_all_sorted.mcep
}

make_units() {
    cat festival/coeffs/cg_all_sorted.{feats,mcep} | cut --complement -f2 -d" " | cut -f1 -d" " | sort -u >festival/disttabs/unittypes
}

make_feats_by_units() {
    UNIT=$1
    SED="/^$UNIT/p"
    TMP=tmp_"$UNIT"_$$
    cat festival/coeffs/cg_all_sorted.feats | cut --complement -f2 -d" " | sed -n $SED | sort >festival/feats/"$UNIT".feats.unsorted
    cat festival/coeffs/cg_all_sorted.mcep | sed -n $SED | sort >festival/feats/"$UNIT".mcep.unsorted
    LINE_FEATS=$(echo "$(wc -l <festival/feats/"$UNIT".feats.unsorted)" - 1 | bc)
    LINE_MCEP=$(echo "$(wc -l <festival/feats/"$UNIT".mcep.unsorted)" - 1 | bc)

    seq 0 "$LINE_FEATS" >$TMP.header.feats
    seq 0 "$LINE_MCEP" >$TMP.header.mcep

    paste -d" " $TMP.header.feats festival/feats/"$UNIT".feats.unsorted >festival/feats/"$UNIT".feats
    paste -d" " $TMP.header.mcep festival/feats/"$UNIT".mcep.unsorted | cut --complement -f1,2 -d" " | $ESTDIR/bin/ch_track -itype ascii -otype est_binary -s 0.005 -o festival/disttabs/"$UNIT".mcep

    $ESTDIR/bin/ch_track -c 0 festival/disttabs/"$UNIT".mcep -otype ascii -o $$.f0
    cut -d " " -f 2- festival/feats/"$UNIT".feats >$$.mcep
    paste -d " " $$.f0 $$.mcep >festival/feats/"$UNIT"_f0.feats
    rm -f $$.f0 $$.mcep

    rm $TMP.*
}

export -f make_feats_by_units

make_all_feats $1
make_units
cat festival/disttabs/unittypes | parallel -j"$CPUS" --bar --progress make_feats_by_units {}
